// <auto-generated />
using System;
using GitHubRepositoryInfo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GitHubRepositoryInfo.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220115223633_MigracaoInicial")]
    partial class MigracaoInicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GitHubRepositoryInfo.Models.FileInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Bytes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Lines")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("RepositoryInfoId")
                        .HasColumnType("bigint");

                    b.Property<string>("Sloc")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryInfoId");

                    b.ToTable("FileInfoItems");
                });

            modelBuilder.Entity("GitHubRepositoryInfo.Models.RepositoryInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("RepositoryInfoItems");
                });

            modelBuilder.Entity("GitHubRepositoryInfo.Models.FileInfo", b =>
                {
                    b.HasOne("GitHubRepositoryInfo.Models.RepositoryInfo", null)
                        .WithMany("FileInfo")
                        .HasForeignKey("RepositoryInfoId");
                });

            modelBuilder.Entity("GitHubRepositoryInfo.Models.RepositoryInfo", b =>
                {
                    b.Navigation("FileInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
